import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Navbar } from '../components/layout/Navbar';
import { PaystackButton } from '../components/billing/PaystackButton';
import { useCredits } from '../hooks/useCredits';
import { useAuthStore } from '../store/authStore';
export function Pricing() {
    const { credits } = useCredits();
    const user = useAuthStore(s => s.user);
    const PACKS = [
        { id: 'starter', name: 'Starter', price: 1500, credits: 30, costPer: '₦50', features: ['30 reply generations', '90 total drafts', 'All 5 tone options', 'Never expires'] },
        { id: 'pro', name: 'Pro', price: 3500, credits: 100, costPer: '₦35', popular: true, features: ['100 reply generations', '300 total drafts', 'All 5 tone options', 'Priority generation', 'Never expires'] },
        { id: 'power', name: 'Power', price: 8000, credits: 300, costPer: '₦27', features: ['300 reply generations', '900 total drafts', 'All 5 tone options', 'Priority generation', 'Never expires'] },
    ];
    return (_jsxs("div", { className: "pricing-page", children: [_jsx(Navbar, {}), _jsxs("main", { className: "pricing-main", children: [_jsxs("div", { className: "pricing-header", children: [_jsx("div", { className: "section-label", children: "Pricing" }), _jsx("h1", { className: "pricing-title", children: "Start free. Pay as you need." }), _jsx("p", { className: "pricing-sub", children: "Everyone gets 5 free reply generations every month. Buy credits when you need more \u2014 they never expire." }), credits && (_jsxs("div", { className: "current-credits", children: ["You currently have ", credits.free > 0 ? `${credits.free} free ${credits.free === 1 ? 'reply' : 'replies'}` : '0 free replies', " remaining", credits.paid > 0 && ` + ${credits.paid} paid credits`, "."] }))] }), _jsx("div", { className: "pricing-cards", children: PACKS.map(pack => (_jsxs("div", { className: `pricing-card ${pack.popular ? 'popular' : ''}`, children: [pack.popular && _jsx("div", { className: "popular-badge", children: "Most popular" }), _jsxs("div", { className: "pricing-card-header", children: [_jsx("span", { className: "pricing-pack-name", children: pack.name }), _jsx("div", { className: "pricing-price", children: _jsxs("span", { className: "pricing-amount", children: ["\u20A6", pack.price.toLocaleString()] }) }), _jsxs("div", { className: "pricing-credits", children: [pack.credits, " credits"] }), _jsxs("div", { className: "pricing-cost-per", children: [pack.costPer, " per reply"] })] }), _jsx("ul", { className: "pricing-features", children: pack.features.map(f => (_jsxs("li", { className: "pricing-feature", children: [_jsx("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2.5", children: _jsx("polyline", { points: "20 6 9 17 4 12" }) }), f] }, f))) }), _jsx("div", { className: "pricing-card-footer", children: user ? (_jsx(PaystackButton, { packId: pack.id, className: "w-full" })) : (_jsx("a", { href: "/app", className: "pricing-signin-cta", children: "Sign in to purchase" })) })] }, pack.id))) }), _jsxs("div", { className: "pricing-faq", children: [_jsx("h2", { className: "faq-title", children: "Common questions" }), [
                                { q: 'Do credits expire?', a: 'Paid credits never expire. Free credits reset on the 1st of every month.' },
                                { q: 'What counts as 1 credit?', a: '1 credit = 1 generation = 3 complete reply drafts delivered simultaneously.' },
                                { q: 'What payment methods work?', a: 'Visa, Mastercard, bank transfer, Verve, and USSD — all handled securely by Paystack.' },
                                { q: 'Can I use it on mobile?', a: 'The web dashboard works on any device. The Gmail extension requires Chrome on desktop.' },
                            ].map(item => (_jsxs("div", { className: "faq-item", children: [_jsx("h3", { className: "faq-q", children: item.q }), _jsx("p", { className: "faq-a", children: item.a })] }, item.q)))] })] })] }));
}
