import React from 'react';
import { Link } from 'react-router-dom';
import { Navbar } from '../components/layout/Navbar';

export function Terms() {
    return (
        <div className="legal-container">
            <Navbar />

            <main className="legal-content">
                <h1>Terms of Service</h1>
                <p className="last-updated">Last Updated: April 29, 2026</p>

                <section>
                    <h2>1. Acceptance of Terms</h2>
                    <p>By accessing or using ReplyAI, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use the service.</p>
                </section>

                <section>
                    <h2>2. Description of Service</h2>
                    <p>ReplyAI is an AI-powered email assistant that provides reply drafts based on email content. The service is provided "as is" and "as available". We do not guarantee the accuracy, completeness, or usefulness of any AI-generated reply.</p>
                </section>

                <section>
                    <h2>3. User Responsibilities</h2>
                    <p>You are solely responsible for the content of the emails you send using drafts generated by ReplyAI. You must review and edit all AI-generated content before sending to ensure accuracy and appropriateness.</p>
                </section>

                <section>
                    <h2>4. Subscription and Credits</h2>
                    <ul>
                        <li>Free users receive a limited quota of monthly credits.</li>
                        <li>Paid credits are purchased as bundles and do not expire.</li>
                        <li>We use Paystack to process payments. You agree to their terms and conditions upon purchase.</li>
                    </ul>
                </section>

                <section>
                    <h2>5. Prohibited Uses</h2>
                    <p>You may not use ReplyAI to generate spam, harassment, or fraudulent content. We reserve the right to terminate accounts that violate these standards.</p>
                </section>

                <section>
                    <h2>6. Limitation of Liability</h2>
                    <p>TrueWeb Solutions shall not be liable for any indirect, incidental, or consequential damages resulting from the use or inability to use the service.</p>
                </section>

                <div style={{ marginTop: '40px' }}>
                    <Link to="/" className="btn-secondary btn-sm">← Back to Home</Link>
                </div>
            </main>
        </div>
    );
}
