import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Modal } from '../ui/Modal';
import { useAuthStore } from '../../store/authStore';
import { CREDIT_PACKS } from '../../types';
import { PaystackButton } from './PaystackButton';
export function PricingModal() {
    const { isPricingOpen, closePricing } = useAuthStore();
    return (_jsxs(Modal, { isOpen: isPricingOpen, onClose: closePricing, maxWidth: "max-w-4xl", children: [_jsxs("div", { className: "text-center mb-10", children: [_jsx("h2", { className: "text-3xl font-display text-white mb-3", children: "Simple, Pay-As-You-Go Pricing" }), _jsx("p", { className: "text-[var(--text-secondary)]", children: "Buy credits once, use them forever. 1 credit = 3 reply drafts." })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: CREDIT_PACKS.map((pack) => (_jsxs("div", { className: `relative bg-[var(--bg-surface)] border ${pack.popular ? 'border-[var(--accent)]' : 'border-[var(--border)]'} rounded-2xl p-6 flex flex-col`, children: [pack.popular && (_jsx("div", { className: "absolute -top-3 left-1/2 -translate-x-1/2 bg-[var(--accent)] text-white text-xs font-bold uppercase tracking-wider py-1 px-3 rounded-full", children: "Most Popular" })), _jsxs("div", { className: "mb-6", children: [_jsx("h3", { className: "text-lg font-medium text-white mb-2", children: pack.name }), _jsx("div", { className: "flex items-baseline gap-1", children: _jsxs("span", { className: "text-4xl font-display font-bold", children: ["\u20A6", pack.price.toLocaleString()] }) }), _jsxs("p", { className: "text-[var(--text-secondary)] mt-2 text-sm", children: [pack.pricePerReply, " per reply equivalent"] })] }), _jsx("div", { className: "flex-grow", children: _jsxs("ul", { className: "space-y-3 mb-8", children: [_jsxs("li", { className: "flex items-center text-sm text-[var(--text-primary)]", children: [_jsx("svg", { className: "w-5 h-5 text-[var(--success)] mr-2 flex-shrink-0", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M5 13l4 4L19 7" }) }), pack.credits, " Credits"] }), _jsxs("li", { className: "flex items-center text-sm text-[var(--text-primary)]", children: [_jsx("svg", { className: "w-5 h-5 text-[var(--success)] mr-2 flex-shrink-0", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M5 13l4 4L19 7" }) }), "Credits never expire"] }), _jsxs("li", { className: "flex items-center text-sm text-[var(--text-primary)]", children: [_jsx("svg", { className: "w-5 h-5 text-[var(--success)] mr-2 flex-shrink-0", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M5 13l4 4L19 7" }) }), "Generate 3 drafts per credit"] })] }) }), _jsx(PaystackButton, { packId: pack.id, className: "w-full mt-auto" })] }, pack.id))) })] }));
}
